spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: db_mongo_rest_api
      username: root
      password: example
      authentication-database: admin
  mvc:
    servlet:
      path: /api/v1


server:
  address: localhost
  port: 12250
  servlet:
    context-path: /mongodb_user

#swagger path
#http://localhost:12210/mongodb_user/api/v1/swagger-ui/index.html
